### ISSUE TITLE
Issue get new JBD BMS working  with internal Bluetooth

### ISSUE THREAD

**Issue by agilastic** [bradcagle/dbus-btbattery#14]
My old JBD-BMS works fine.

I upgraded my battery system with a news JBD BMS and new batteries.

./scan.py #results:
Device a4:c1:37:53:21:45 (public), RSSI=-67 dB
  Flags = 05
  Incomplete 16b Services = 0000ff00-0000-1000-8000-00805f9b34fb
  Complete Local Name = **AP21S002P21200A**
  Manufacturer = 45215337c1a4

I can't get it run. JBD might has changed something. Here is my output: 
#
# I uncommented print(hex_string) in line 133 and  
# and  added      at pos:
#        # Hack
#                elif len(data) == 20:
#                       if self.cellData == None:
#                                pprint("self.CellData == None")

root@raspberrypi4:/opt/victronenergy/dbus-btbattery# /opt/victronenergy/dbus-btbattery/dbus-btbattery.py a4:c1:37:53:21:45
INFO:BluetoothBattery:Starting dbus-btbattery
INFO:BluetoothBattery:dbus-btbattery v0.1.3
INFO:BluetoothBattery:Connecting a4:c1:37:53:21:45
INFO:BluetoothBattery:0.0013429630000700854
INFO:BluetoothBattery:0.002221575000021403
INFO:BluetoothBattery:Connected a4:c1:37:53:21:45
00
dd0400200d060d0e0d0d0d070d080d060d080d08
0d0a0d080d070d080d080d0a0d0c0d0afe8177
dd03002214db00005ca3753000002f7200000000
1000564f0110010b1e00000075305ca30000fa16
'self.CellData == None'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/victronenergy/dbus-btbattery/jbdbt.py", line 106, in run
    while self.bt.waitForNotifications(4):
  File "/usr/lib/python3.8/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/usr/lib/python3.8/site-packages/bluepy/btle.py", line 416, in _getResp
    self.delegate.handleNotification(hnd, data)
  File "/opt/victronenergy/dbus-btbattery/jbdbt.py", line 161, in handleNotification
    self.cellData = self.cellData + data
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'

Any ideas?

**Comment by agilastic** [comment]
Ok I got it.  
If you need more details what I've done, see my fork and last commit. Works so far:
https://github.com/agilastic/dbus-btbattery/commit/1258e35d09016c18fe5d91922afc0c56fcdc931d

**Comment by bradcagle** [comment]
Great I'll take a look, and test with my BMSs here.

Thanks

**Comment by dsrawding** [comment]
FYI, I have two 2024 batteries with the new JDB BMSs.  Had the same problem as agilastic.  Added his changes and I'm up and running!

**Comment by D0T-C0M** [comment]
I tried both Brad's and agilastic's version on my VenusGX v3.31 and my JBD-SP04S060-300A-L4S BMS will connect after several tries and is detected in Victron's GUI but shortly after it connects it just disconnects and tries to reconnect and after several failed attempts it reconnects and it will reconnect and disconnect 3 or 4 times then the bluetooth locks up and the raspberrypi reboots.  The RPi is right up close to the BMS. 

`
root@raspberrypi4:/opt/victronenergy/dbus-btbattery# ./dbus-btbattery.py a4:c1:37:23:9d:11
INFO:BluetoothBattery:Starting dbus-btbattery
INFO:BluetoothBattery:dbus-btbattery v0.1.3
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:0.0013103509991196916
INFO:BluetoothBattery:0.002120574004948139
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:60.083996482004295
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connected a4:c1:37:23:9d:11
INFO:BluetoothBattery:new Hex_String(1): 00
INFO:BluetoothBattery:new Hex_String(15): dd0400080cdf0cdf0cdf0ce2fc4977
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b7e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b7e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f91577
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b7e0b820b7f0000007a0f40ae8110f91577
INFO:BluetoothBattery:0.5808614450070309
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:Battery JBD BT connected to dbus from /bta4c137239d11
INFO:BluetoothBattery:=== Settings ===
INFO:BluetoothBattery:> Connection voltage 13.18V | current 0.0A | SOC 53%
INFO:BluetoothBattery:> Cell count 4 | cells populated 4
INFO:BluetoothBattery:> CCCM SOC True | DCCM SOC True
INFO:BluetoothBattery:> CCCM CV True | DCCM CV True
INFO:BluetoothBattery:> CCCM T True | DCCM T True
INFO:BluetoothBattery:> MIN_CELL_VOLTAGE 2.9V | MAX_CELL_VOLTAGE 3.45V
INFO:BluetoothBattery:DeviceInstance = 1
INFO:BluetoothBattery:com.victronenergy.battery.bta4c137239d11
INFO:BluetoothBattery:publish config values = 1
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b7e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b7e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f91577
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b7e0b820b7f0000007a0f40ae8110f91577
INFO:BluetoothBattery:0.2845447779982351
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b7d0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b7d0b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f91677
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b7d0b820b7f0000007a0f40ae8110f91677
INFO:BluetoothBattery:0.960999481001636
INFO:BluetoothBattery:new Hex_String(15): dd0400080cdf0cdf0cdf0ce0fc4b77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b7d0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b7d0b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f91677
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b7d0b820b7f0000007a0f40ae8110f91677
INFO:BluetoothBattery:0.6142261849890929
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b900b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b900b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f90377
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b900b820b7f0000007a0f40ae8110f90377
INFO:BluetoothBattery:0.24297583299630787
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b900b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b900b820b7f0000007a0f40ae
INFO:BluetoothBattery:0.9192827770020813
INFO:BluetoothBattery:new Hex_String(5): 8110f90377
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b900b820b7f0000007a0f40ae8110f90377
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:0.9178069439949468
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b8f0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b8f0b820b7f0000007a0f40ae
INFO:BluetoothBattery:0.5466152590088313
INFO:BluetoothBattery:new Hex_String(5): 8110f90477
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b8f0b820b7f0000007a0f40ae8110f90477
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:0.5457492770074168
INFO:BluetoothBattery:120.21957231700071
INFO:BluetoothBattery:new Hex_String(20): dd0300260525000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b8e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260525000040ae753000012eb000000000000041350304030b8e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:0.17723509199277032
INFO:BluetoothBattery:new Hex_String(5): 8110f90677
INFO:BluetoothBattery:Final Length generalData(45): dd0300260525000040ae753000012eb000000000000041350304030b8e0b820b7f0000007a0f40ae8110f90677
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:0.17591579600411933
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b8e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b8e0b820b7f0000007a0f40ae
INFO:BluetoothBattery:0.8525660360028269
INFO:BluetoothBattery:new Hex_String(5): 8110f90577
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b8e0b820b7f0000007a0f40ae8110f90577
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0cdffc4d77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:0.851421498999116
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b8d0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b8d0b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f90677
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b8d0b820b7f0000007a0f40ae8110f90677
INFO:BluetoothBattery:0.458915277995402
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:new Hex_String(20): dd0300260526000040ae753000012eb000000000
INFO:BluetoothBattery:generalDataTotalLen: 45
INFO:BluetoothBattery:generalDataRemainingLen: 25
INFO:BluetoothBattery:new Hex_String(20): 000041350304030b8c0b820b7f0000007a0f40ae
INFO:BluetoothBattery:Final Length generalData(40): dd0300260526000040ae753000012eb000000000000041350304030b8c0b820b7f0000007a0f40ae
INFO:BluetoothBattery:new Hex_String(5): 8110f90777
INFO:BluetoothBattery:Final Length generalData(45): dd0300260526000040ae753000012eb000000000000041350304030b8c0b820b7f0000007a0f40ae8110f90777
INFO:BluetoothBattery:0.11145981500158086
INFO:BluetoothBattery:new Hex_String(15): dd0400080cde0cdf0cdf0ce0fc4c77
INFO:BluetoothBattery:cellDataTotalLen: 15
INFO:BluetoothBattery:cellDataRemainingLen: 0
INFO:BluetoothBattery:Disconnected
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
INFO:BluetoothBattery:Connecting a4:c1:37:23:9d:11
INFO:BluetoothBattery:Connection failed: Failed to connect to peripheral a4:c1:37:23:9d:11, addr type: public
`

**Comment by zschramm** [comment]
HI, thank you for providing the fix for this, hopefully brad has time to review and merge.

However I see this warning when, something we should fix?

WARNING:root:USING OUTDATED REGISTRATION METHOD!
WARNING:root:Please set register=False, then call the register method after adding all mandatory paths. See https://github.com/victronenergy/venus/wiki/dbus-api

**Comment by WP-Rue** [comment]
Hi, same problem here:
I used the fork of @agilastic ..

> WARNING:root:USING OUTDATED REGISTRATION METHOD!
> WARNING:root:Please set register=False, then call the register method after adding all mandatory paths. See https://github.com/victronenergy/venus/wiki/dbus-api
> INFO:BluetoothBattery:Setting up D-Bus paths for virtual battery
> ERROR:BTBattery:Error creating DBUS service: 'JbdBt' object has no attribute 'min_battery_voltage'
> ERROR:BTBattery:Failed to create DBUS service, exiting.

Venus OS3.54 Large

Maybe I found a solution here:

[https://github.com/sebdehne/dbus-mqtt-services/commit/eea330dda33f1aa91c2f6e9a718723dfccb4af0a](url)

But maybe only the 'min_battery_voltage' is missing...?

But I have not the skills to fix this. Anybody else able to help?

**Comment by bradcagle** [comment]
@WP-Rue Have you tried the original repo? https://github.com/bradcagle/dbus-btbattery

**Comment by agilastic** [comment]
Hi there I've activated issues for my forked repo: https://github.com/agilastic/dbus-btbattery/issues
to keep it clean here  =;-)

**Comment by WP-Rue** [comment]
> [@WP-Rue](https://github.com/WP-Rue) Have you tried the original repo? https://github.com/bradcagle/dbus-btbattery

So- now I tried.
It seems to work, a lot of connecting and disconnecting.. but finally data arrived in remote console (I have to adapt the config, because I use a Li-Ion no LFP)

> NFO:BluetoothBattery:Disconnected
> INFO:BluetoothBattery:Connecting a5:c2:37:27:04:f4
> INFO:BluetoothBattery:Connected a5:c2:37:27:04:f4
> INFO:BluetoothBattery:generalDataTotalLen: 45
> INFO:BluetoothBattery:generalData(45): dd030026111400000d481b580000309b0000000010003831010c030b610b4f0b4f0000001b580d480000fbb177
> INFO:BluetoothBattery:cellDataTotalLen: 31
> INFO:BluetoothBattery:cellData(31): dd0400180e380e3e0e390e3e0e380e3b0e3b0e3c0e3c0e3d0e3b0e3dfc7877
> INFO:BluetoothBattery:Battery JBD BT connected to dbus from /bta5c2372704f4
> INFO:BluetoothBattery:=== Settings ===
> INFO:BluetoothBattery:> Connection voltage 43.72V | current 0.0A | SOC 49%
> INFO:BluetoothBattery:> Cell count 12 | cells populated 12
> INFO:BluetoothBattery:> CCCM SOC True | DCCM SOC True
> INFO:BluetoothBattery:> CCCM CV True | DCCM CV True
> INFO:BluetoothBattery:> CCCM T True | DCCM T True
> INFO:BluetoothBattery:> MIN_CELL_VOLTAGE 2.9V | MAX_CELL_VOLTAGE 3.45V
> WARNING:root:USING OUTDATED REGISTRATION METHOD!
> WARNING:root:Please set register=False, then call the register method after adding all mandatory paths. See https://github.com/victronenergy/venus/wiki/dbus-api
> INFO:BluetoothBattery:DeviceInstance = 3
> INFO:BluetoothBattery:com.victronenergy.battery.bta5c2372704f4
> INFO:BluetoothBattery:publish config values = 1
> INFO:BluetoothBattery:Disconnected
> INFO:BluetoothBattery:Connecting a5:c2:37:27:04:f4
> INFO:BluetoothBattery:Connected a5:c2:37:27:04:f4
> INFO:BluetoothBattery:Disconnected
> INFO:BluetoothBattery:Connecting a5:c2:37:27:04:f4
> INFO:BluetoothBattery:Connected a5:c2:37:27:04:f4
> INFO:BluetoothBattery:Disconnected
> INFO:B

But during writing this I have a reboot! That is not good in my setup, because I do a lot of things in node red, and rebooting always needs some manual action to make a full restart. (Wallbox, heat pump switching conditions...)

I have to prevent this restart.


> NFO:BluetoothBattery:Connecting a5:c2:37:27:04:f4
INFO:BluetoothBattery:Connected a5:c2:37:27:04:f4
INFO:BluetoothBattery:Disconnected
INFO:BluetoothBattery:Connecting a5:c2:37:27:04:f4
INFO:BluetoothBattery:Watchdog timer expired. BT chipset might be locked up. Rebooting
