### ISSUE TITLE
Attribute can't be written

### ISSUE THREAD

**Issue by Bitbanger1900** [bradcagle/dbus-btbattery#5]
Hi,

happy to find finally something to get my JBD into VenusOS so many thanks!

I can see the BMS but i get the following error when i try to connect.

INFO:BluetoothBattery:Connected C8:47:8C:E9:3C:F4
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/home/root/dbus-btbattery/jbdbt.py", line 92, in run
    result = self.bt.writeCharacteristic(0x15, b'\xdd\xa5\x03\x00\xff\xfd\x77', True)	# write x03 (general info)
  File "/usr/lib/python3.8/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/lib/python3.8/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/lib/python3.8/site-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 3, error: Attribute can't be written)

Regards,
Hannes

**Comment by bradcagle** [comment]
The driver only supports JBD right now, your JK will not work ATM. Hopefully I can get some time to add other BMSs
